# Generated by Django 2.1.3 on 2019-04-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='日志时间')),
                ('log_info', models.CharField(max_length=1000, verbose_name='日志内容')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(max_length=200, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=200, verbose_name='姓名')),
                ('stu_tel', models.CharField(max_length=200, verbose_name='电话')),
                ('stu_email', models.CharField(max_length=200, verbose_name='邮箱')),
                ('stu_info', models.CharField(default='少年，我看好你哦,这学期的python成绩是balabalaballa!', max_length=1000, verbose_name='信息')),
                ('stu_password', models.CharField(default='123456', max_length=200, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_info.User'),
        ),
    ]
