# Generated by Django 2.1.3 on 2019-04-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0002_auto_20190405_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stu_intro',
            field=models.CharField(default='熟悉的城市啊~~~，我要金坷垃', max_length=1000),
        ),
    ]
