# Generated by Django 2.1.3 on 2019-04-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0003_user_stu_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stu_qq',
            field=models.CharField(default='', max_length=200),
        ),
    ]
