# Generated by Django 2.1.3 on 2019-04-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0004_user_stu_qq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000, verbose_name='描述')),
                ('mark', models.FloatField(verbose_name='分数')),
                ('result', models.CharField(max_length=200, verbose_name='答案')),
            ],
        ),
        migrations.CreateModel(
            name='Usertopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField(verbose_name='结果')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_info.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='stu_intro',
            field=models.CharField(default='熟悉的城市啊~~~，我要金坷垃', max_length=1000, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stu_qq',
            field=models.CharField(default='', max_length=200, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='usertopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_info.User'),
        ),
        migrations.AddField(
            model_name='topic',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_info.Work'),
        ),
    ]
