# Generated by Django 2.1.3 on 2019-04-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0005_auto_20190410_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='answer',
            field=models.CharField(default='', max_length=200, verbose_name='答案'),
        ),
        migrations.AddField(
            model_name='work',
            name='is_show',
            field=models.IntegerField(default=1, verbose_name='是否展示，1展示，0不展示'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='result',
            field=models.CharField(default='', max_length=200, verbose_name='答案'),
        ),
    ]
