# Generated by Django 2.1.3 on 2019-04-10 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0006_auto_20190410_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 6, 44, 22, 107750, tzinfo=utc)),
        ),
    ]
