# Generated by Django 2.1.3 on 2019-04-10 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0007_work_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopic',
            name='result',
            field=models.IntegerField(default=0, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='work',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 8, 55, 5, 46805, tzinfo=utc)),
        ),
    ]
