# Generated by Django 2.1.3 on 2019-04-10 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0008_auto_20190410_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='mark',
            field=models.FloatField(default=0, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='work',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 9, 0, 12, 668088, tzinfo=utc)),
        ),
    ]
